# Generated by Django 4.2.17 on 2025-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Nuevo Mensaje'), ('resena', 'Nueva Reseña'), ('trabajo', 'Nuevo Trabajo'), ('pago', 'Pago Recibido'), ('sistema', 'Notificación del Sistema')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, max_length=500, verbose_name='Enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
