# Generated by Django 4.2.17 on 2025-11-27 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('periodo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20, verbose_name='Periodo')),
                ('destacar_perfil', models.BooleanField(default=False, verbose_name='Destacar Perfil')),
                ('apariciones_top', models.BooleanField(default=False, verbose_name='Apariciones en Top')),
                ('insignia_premium', models.BooleanField(default=False, verbose_name='Insignia Premium')),
                ('soporte_prioritario', models.BooleanField(default=False, verbose_name='Soporte Prioritario')),
                ('estadisticas_avanzadas', models.BooleanField(default=False, verbose_name='Estadísticas Avanzadas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'planes_suscripcion',
                'ordering': ['orden', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pendiente', 'Pendiente de Pago')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('renovacion_automatica', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='suscripciones.suscripcion')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
