# Generated by Django 4.2.17 on 2025-11-27 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plansuscripcion'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['usuario', 'estado'], name='suscripcion_usuario_4636d8_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['fecha_fin'], name='suscripcion_fecha_f_89a762_idx'),
        ),
    ]
