# Generated by Django 4.2.17 on 2026-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_materiales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_estimado_horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vigencia_horas',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_maxima_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='modalidad',
            field=models.CharField(choices=[('domicilio', 'A domicilio'), ('presencial', 'Presencial'), ('remoto', 'Remoto')], default='domicilio', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('programado', 'Programado')], default='normal', max_length=20),
        ),
    ]
