# Generated by Django 4.2.17 on 2026-05-22 05:30

import apps.seguridad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_cotizacion_incluye_materiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=apps.seguridad.fields.EncryptedTextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=apps.seguridad.fields.EncryptedTextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='detalles_adicionales',
            field=apps.seguridad.fields.EncryptedTextField(blank=True, max_length=4096),
        ),
    ]
