# Generated by Django 4.2.17 on 2026-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_alter_cotizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='firma',
            field=models.TextField(blank=True, verbose_name='Firma Digital'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hash_integridad',
            field=models.CharField(blank=True, max_length=64, verbose_name='Hash de Integridad SHA-256'),
        ),
    ]
