# Generated by Django 4.2.17 on 2026-05-22 05:30

import apps.seguridad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=apps.seguridad.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Teléfono'),
        ),
    ]
