# Generated by Django 4.2.17 on 2025-11-27 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('carpinteria', 'Carpintería'), ('albañileria', 'Albañilería'), ('pintura', 'Pintura'), ('jardineria', 'Jardinería'), ('limpieza', 'Limpieza'), ('mecanica', 'Mecánica'), ('tecnologia', 'Tecnología'), ('otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('especialidades', models.JSONField(default=list, verbose_name='Especialidades')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('zona_servicio', models.JSONField(default=list, verbose_name='Zonas de Servicio')),
                ('tarifa_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por Hora')),
                ('tarifa_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa Mínima')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Promedio')),
                ('total_trabajos', models.PositiveIntegerField(default=0, verbose_name='Total de Trabajos')),
                ('total_resenas', models.PositiveIntegerField(default=0, verbose_name='Total de Reseñas')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('horario_disponibilidad', models.JSONField(default=dict, verbose_name='Horario de Disponibilidad')),
                ('identidad_verificada', models.BooleanField(default=False, verbose_name='Identidad Verificada')),
                ('domicilio_verificado', models.BooleanField(default=False, verbose_name='Domicilio Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Trabajador',
                'verbose_name_plural': 'Perfiles de Trabajadores',
                'db_table': 'perfiles_trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_media', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=20, verbose_name='Tipo de Media')),
                ('archivo', models.FileField(upload_to='portafolios/%Y/%m/', verbose_name='Archivo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='perfiles.perfiltrabajador')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': 'portafolios',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
