# Generated by Django 4.2.17 on 2025-11-27 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_trabajador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='perfiltrabajador',
            index=models.Index(fields=['categoria'], name='perfiles_tr_categor_80e9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='perfiltrabajador',
            index=models.Index(fields=['calificacion_promedio'], name='perfiles_tr_calific_ea6b86_idx'),
        ),
        migrations.AddIndex(
            model_name='perfiltrabajador',
            index=models.Index(fields=['disponible'], name='perfiles_tr_disponi_7c94e7_idx'),
        ),
    ]
