# Generated by Django 4.2.17 on 2026-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='certificaciones',
            field=models.JSONField(default=list, verbose_name='Certificaciones'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='herramientas',
            field=models.JSONField(default=list, verbose_name='Herramientas / Equipo'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='idiomas',
            field=models.JSONField(default=list, verbose_name='Idiomas'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='modalidades_servicio',
            field=models.JSONField(default=list, verbose_name='Modalidades de Servicio'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='tiempo_respuesta_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='Tiempo de Respuesta (horas)'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='titulo_profesional',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Título Profesional'),
        ),
    ]
