# Generated by Django 4.2.17 on 2026-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfiltrabajador_certificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='categorias',
            field=models.JSONField(default=list, verbose_name='Categorías'),
        ),
    ]
