# Generated by Django 4.2.17 on 2026-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_perfiltrabajador_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/portadas/', verbose_name='Foto de Portada'),
        ),
    ]
