# Generated by Django 4.2.17 on 2026-05-22 05:30

import apps.seguridad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=apps.seguridad.fields.EncryptedTextField(max_length=4096, verbose_name='Contenido'),
        ),
    ]
