# Generated by Django 4.2.17 on 2025-11-27 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('verificada', models.BooleanField(default=False, verbose_name='Verificada')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('util_count', models.PositiveIntegerField(default=0, verbose_name='Votos Útiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'resenas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotoUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='resenas.resena')),
            ],
            options={
                'verbose_name': 'Voto Útil',
                'verbose_name_plural': 'Votos Útiles',
                'db_table': 'votos_utiles',
            },
        ),
    ]
