# Generated by Django 4.2.17 on 2025-11-27 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0002_initial'),
        ('resenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votoutil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='resena',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='perfiles.perfiltrabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='votoutil',
            unique_together={('resena', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['trabajador', '-created_at'], name='resenas_trabaja_a2f391_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['calificacion'], name='resenas_calific_a89caf_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['verificada'], name='resenas_verific_5b27c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('cliente', 'trabajador')},
        ),
    ]
